#!/usr/bin/env python3

#
# EPITECH PROJECT, 2017
# 103cipher_2017
# File description:
# Main function for the 103cipher project
#

import sys

def main():
	message = sys.argv[1]
	key = sys.argv[2]
	option = sys.argv[3]
	if option == "0":
		encryption(sys.argv[1], sys.argv[2])
	else:
		sys.exit(84)

def encryption(message, key):
	key_length = len(key)
	key_size = 0
	message_size = 0
	key_matrix = []
	message_matrix = []
	result_matrix = []
	result_row = []
	i = 0
	# Create the key matrix
	while key_size*key_size < len(key):
		key_size += 1
	for x in range(key_size):
		key_row = []
		for y in range(key_size):
			if i != len(key):
				key_row.append(ord(key[i]))
				i += 1
			else:
				key_row.append(0)
		key_matrix.append(key_row)
	# Create the message matrix
	i = 0
	while key_size*message_size < len(message):
		message_size += 1
	for x in range(message_size):
		message_row = []
		result_row = []
		for y in range(key_size):
			if i != len(message):
				message_row.append(ord(message[i]))
				i += 1
			else:
				message_row.append(0)
			result_row.append(0)
		message_matrix.append(message_row)
		result_matrix.append(result_row)
	# Multiply both matrix to create the result_matrix
	i = 0
	result_matrix = [[sum([message_matrix[i][m]*key_matrix[m][j]
					for m in range(len(message_matrix[0]))])
					for j in range(len(key_matrix[0]))]
					for i in range(len(message_matrix))]
	# Print key matrix then encrypted message
	print(f"Key matrix :")
	for row in key_matrix:
		print(*row, sep='	')
	print(f"Encrypted message :")
	i = 0
	for row in result_matrix:
		if i == 0:
			print(*row, end='')
			i = 1
		else:
			print('', *row, end='')

if __name__ == "__main__":
	main()
